### ISSUE TITLE
Plugins: require currently editing user to be on author list

### ISSUE THREAD

**Issue by thermokarst** [qiime2/library-old#19]
**Bug Description**
Users creating (or editing) a plugin should be required to be in the author list --- without it, someone can create a plugin and not be able to continue editing after saving the record.

**References**
1. [Forum](https://forum.qiime2.org/t/qiime-2-library/6327/3?u=thermokarst)

**Comment by J1411** [comment]
Thanks for creating this issue! We have already started work on it and will update you once we have any questions and/or the proposed solution.

**Comment by thermokarst** [comment]
Fixed in #22
